package model;

public enum EVENT {
    INIT_GAME,
    EXIT_GAME,
    ALL_PLAYERS_CONNECT,
    CONNECT_PLAYER,
    DISCONNECT_PLAYER,
    NEXT_TURN,
    NEXT_ROUND,
    LOAD_GAME,
    SAVE_GAME,
    PLAYER_RECEIVE_DAMAGE,
    PLAYER_TAKE_HEAP
}
