package model.enums;

public enum EVENT {
    EXIT_GAME,
    ALL_PLAYERS_CONNECT,
    CONNECT_PLAYER,
    DISCONNECT_PLAYER,
    PLAYER_PLAYED_CARD,
    NEXT_TURN,
    NEXT_ROUND,
    LOAD_GAME,
    SAVE_GAME,
    RESET_GAME,
    WINNER,
    PLAYER_TAKE_HEAP
}
