package model.enums;

public enum EVENT {
    CLOSE_GAME,
    ALL_PLAYERS_CONNECT,
    CONNECT_PLAYER,
    PLAYER_PLAYED_CARD,
    NEXT_TURN,
    NEXT_ROUND,
    RESET_GAME,
    WINNER,
    PLAYER_TAKE_HEAP
}
